baseURL: "https://shaodong.name"
languageCode: "en-us"
title: "Shaodong's Blog"
theme: "TeXtLite"
disqusShortname: "disqus-shortname-here"
footnoteReturnLinkContents: "↩"

permalinks:
  post: /:year/:month/:day/:filename/

outputFormats:
  RSS:
    baseName: feed
    mediaType: application/rss

summaryLength: 80

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Posts"
      url: "/post/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 4
    - name: "Subscribe"
      url: "/feed.xml"

params:
  description: "About Learning"
  social: 
    email: " "
    github: " "
    facebook: " "
    twitter: " "
  icon:
    logo: "/themes/TeXtLite/static/logo.svg"
    email: "/themes/TeXtLite/static/social/email.svg"
    twitter: "/themes/TeXtLite/static/social/twitter.svg"
    github: "/themes/TeXtLite/static/social/github.svg"
    facebook: "/themes/TeXtLite/static/social/facebook.svg"
  comments:
    utterances: "liao961120/comments"
    disqus: "y-f-liao-s-page"
    # Comment systems to include by default
    default:
      - utterances

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: monokai
    tabWidth: 4
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
